import Head from 'next/head'
import styles from '../../styles/Home.module.css'

import dynamic from 'next/dynamic'

// @ts-ignore
const Parcel = dynamic(() => import("app1/Parcel"), { ssr: false, loading: () => <div>Carregando...</div> })

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Parcel />
        NextJS main consumer
      </main>
    </div>
  )
}
